'\" t
.\"     Title: amqp-delete-queue
.\"    Author: The RabbitMQ Team <\m[blue]\fBinfo@rabbitmq.com\fR\m[]>
.\" Generator: DocBook XSL Stylesheets v1.75.2 <http://docbook.sf.net/>
.\"      Date: 2016-12-29
.\"    Manual: RabbitMQ C Client
.\"    Source: RabbitMQ C Client
.\"  Language: English
.\"
.TH "AMQP\-DELETE\-QUEUE" "1" "2016\-12\-29" "RabbitMQ C Client" "RabbitMQ C Client"
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
amqp-delete-queue \- Delete a queue from an AMQP server
.SH "SYNOPSIS"
.HP \w'\fBamqp\-delete\-queue\fR\ 'u
\fBamqp\-delete\-queue\fR [\fIOPTION\fR...] {\-q\ \fIqueue\ name\fR}
.SH "DESCRIPTION"
.PP

\fBamqp\-delete\-queue\fR
deletes a queue from an AMQP server, and exits after printing to standard output the number of messages that were in the queue at the time of its deletion\&.
.SH "OPTIONS"
.PP
\fB\-q\fR, \fB\-\-queue\fR=\fIqueue name\fR
.RS 4
The name of the queue to delete\&.
.RE
.SH "EXIT STATUS"
.PP
If the queue was successfully deleted, the exit status is 0\&. If an error occurs, the exit status is 1\&.
.SH "EXAMPLES"
.PP
Delete the queue \(lqmyqueue\(rq at a moment when it has 123 messages waiting on it:
.RS 4
.sp
.if n \{\
.RS 4
.\}
.nf
$ \fBamqp\-delete\-queue \-q myqueue\fR
123
.fi
.if n \{\
.RE
.\}
.RE
.SH "SEE ALSO"
.PP

\fBlibrabbitmq-tools\fR(7)
describes connection\-related options common to all the RabbitMQ C Client tools\&.
.SH "AUTHOR"
.PP
\fBThe RabbitMQ Team <\fR\fB\m[blue]\fBinfo@rabbitmq\&.com\fR\m[]\fR\fB>\fR
